### ISSUE TITLE
Poor domain logic

### ISSUE THREAD

**Issue by damianopetrungaro** [pmjones/adr-example#1]
Hey @pmjones the example it's well structured and easy to understand, but i think this it's not a real domain with real complex logic.
Are you planning to do some real-world and handle some domain complexity?
If help needed ping me 😄

**Comment by pmjones** [comment]
> not a real domain with real complex logic

Correct; I figure it's more important to showcase the separations, rather than be an example of a full DDD domain layer.

> Are you planning to do some real-world and handle some domain complexity?

I was not planning on it, no.

Having said that, if you feel the urge to put something together, I'll be happy to review a PR!

**Comment by damianopetrungaro** [comment]
Sure i'll send some PR

**Comment by damianopetrungaro** [comment]
@pmjones  sorry but as you can see I had no time for this 😅 

Let's close it, thank you for the reply anyway 😄
